import type { Metadata } from "next";
import { Jost } from "next/font/google";

import { NuqsAdapter } from "nuqs/adapters/next/app";

import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/client";

import "./globals.css";

const font = Jost({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Ultimate Shop",
  description: "Generated by create next app",
};

export default function ({ children }: React.PropsWithChildren) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn("antialiased", font.className)}>
        <NuqsAdapter>
          <TRPCReactProvider>
            {children}
            <Toaster
              toastOptions={{ className: font.className }}
              richColors
              theme="light"
            />
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
