import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";

import { Toaster } from "@/components/ui/sonner";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { cn } from "@/lib/utils";

import "./globals.css";

const font = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: React.PropsWithChildren) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn("antialiased", font.className)}>
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
          <Toaster
            toastOptions={{ className: font.className }}
            theme="light"
            richColors
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
